name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Optional: Push Docker image to a registry like Docker Hub
      # - name: Push Docker image
      #   run: |
      #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #     docker tag my-web-app ${{ secrets.DOCKER_USERNAME }}/my-web-app
      #     docker push ${{ secrets.DOCKER_USERNAME }}/my-web-app
      
      - name: Deploy to AWS ECS
        env:
          AWS_REGION: us-west-2  # Set your AWS region
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Build Docker image (if not already built in CI)
          docker build -t my-web-app .
          
          # AWS ECS deployment
          # Ensure AWS CLI is configured with appropriate credentials and region
          
          # Example ECS deployment command:
          aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment
